
"use client";

import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { usePathname } from "next/navigation";
import { MainLayout } from "@/components/main-layout";

// Note: Metadata cannot be exported from a client component. 
// If you need dynamic metadata, you'll need a different approach.
// export const metadata: Metadata = {
//   title: 'Firebase Studio App',
//   description: 'Generated by Firebase Studio',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isLoginPage = pathname === "/login";

  return (
    <html lang="en">
      <head>
        <title>Vedi - Therapy Practice Manager</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        {isLoginPage ? (
          children
        ) : (
          <MainLayout>
            {children}
          </MainLayout>
        )}
        <Toaster />
      </body>
    </html>
  );
}
